name: CwVideo
author: mario_fischer
category: Media
tags: [video, html5, player, media, control, slider, timeline]
demo: http://www.chipwreck.de/blog/software/cwvideo/demo/
docs: http://www.chipwreck.de/blog/software/cwvideo/help/
current: 0.5
